export const POKEMONDATASAVE_REQUEST = 'POKEMONDATASAVE_REQUEST';
export const POKEMONDATASAVE_SUCCESS = 'POKEMONDATASAVE_SUCCESS';

export const POKEMONSEARCHINPUT_REQUEST = 'POKEMONDATASAVE_REQUEST';
export const POKEMONSEARCHINPUT_SUCCESS = 'POKEMONSEARCHINPUT_SUCCESS';

export const SORTAZ_REQUEST = 'SORTAZ_REQUEST';
export const SORTAZ_SUCCESS = 'SORTAZ_SUCCESS';

export const SORT19_REQUEST = 'SORT19_REQUEST';
export const SORT19_SUCCESS = 'SORT19_SUCCESS';

export const SORTMENU_SUCCESS = 'SORTMENU_SUCCESS';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';
