export const SORTAZ_REQUEST = 'SORTAZ_REQUEST';
export const SORTAZ_SUCCESS = 'SORTAZ_SUCCESS';

export const POKEMONDATASAVE_REQUEST = 'POKEMONDATASAVE_REQUEST';
export const POKEMONDATASAVE_SUCCESS = 'POKEMONDATASAVE_SUCCESS';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';
